apiVersion: v1
kind: Service
metadata:
  name: peer0-dfarmretail
  labels:
    run: peer0-dfarmretail
spec:
  type: ClusterIP 
  selector:
    name: peer0-dfarmretail
  ports:
  - protocol: TCP
    port: 7051
    name: grpc
  - protocol: TCP
    port: 7061
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb