Organizations:
  - &orderer
    Name: orderer
    ID: orderer
    MSPDir: crypto-config/ordererOrganizations/default.svc.cluster.local/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('orderer.member')"
      Writers:
        Type: Signature
        Rule: "OR('orderer.member')"
      Admins:
        Type: Signature
        Rule: "OR('orderer.admin')"

  - &dfarmadmin
    Name: dfarmadmin
    ID: dfarmadmin
    MSPDir: crypto-config/peerOrganizations/dfarmadmin/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('dfarmadmin.admin', 'dfarmadmin.peer', 'dfarmadmin.client', 'dfarmadmin.member')"
      Writers:
        Type: Signature
        Rule: "OR('dfarmadmin.admin', 'dfarmadmin.peer', 'dfarmadmin.client', 'dfarmadmin.member')"
      Admins:
        Type: Signature
        Rule: "OR('dfarmadmin.admin')"
    AnchorPeers:
      - Host: peer0-dfarmadmin-service
        Port: 7051

  - &dfarmretail
    Name: dfarmretail
    ID: dfarmretail
    MSPDir: crypto-config/peerOrganizations/dfarmretail/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('dfarmretail.admin', 'dfarmretail.peer', 'dfarmretail.client', 'dfarmretail.member')"
      Writers:
        Type: Signature
        Rule: "OR('dfarmretail.admin', 'dfarmretail.peer', 'dfarmretail.client', 'dfarmretail.member')"
      Admins:
        Type: Signature
        Rule: "OR('dfarmretail.admin')"
    AnchorPeers:
      - Host: peer0-dfarmretail-service
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V1_4_3: true

  Orderer: &OrdererCapabilities
    V1_4_2: true

  Application: &ApplicationCapabilities
    V1_4_2: true

Application: &ApplicationDefaults
  Organizations:
    - *orderer
    - *dfarmadmin
    - *dfarmretail

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer0-service
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/default.svc.cluster.local/orderers/orderer0.default.svc.cluster.local/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/default.svc.cluster.local/orderers/orderer0.default.svc.cluster.local/tls/server.crt
      - Host: orderer1-service
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/default.svc.cluster.local/orderers/orderer1.default.svc.cluster.local/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/default.svc.cluster.local/orderers/orderer1.default.svc.cluster.local/tls/server.crt
      - Host: orderer2-service
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/default.svc.cluster.local/orderers/orderer2.default.svc.cluster.local/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/default.svc.cluster.local/orderers/orderer2.default.svc.cluster.local/tls/server.crt
  Addresses:
    - orderer0-service:7050
    - orderer1-service:7050
    - orderer2-service:7050
  
  BatchTimeout: 1s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Kafka:
    Brokers:
      - 127.0.0.1:9092
  
  Organizations:
    - *orderer
  
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:

  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *orderer
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *orderer
    Consortiums:
      Dfarm:
        Organizations:
          - *dfarmadmin
          - *dfarmretail

  dfarmchannel:
    <<: *ChannelDefaults
    Consortium: Dfarm
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *dfarmadmin
        - *dfarmretail
      Capabilities:
        <<: *ApplicationCapabilities
